### ISSUE TITLE
Okta Factors should show Profile Properties like the Okta Devices schema.

### ISSUE THREAD

**Issue by mattjurczyk** [turbot/steampipe-plugin-okta#129]
**Describe the bug**

**Steampipe version (`steampipe -v`)**
Example: v0.3.0
Newest
**Plugin version (`steampipe plugin list`)**
Example: v0.5.0
newest
**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

select * from okta_factor
**Expected behavior**
results should show profile fields rather than null.
**Additional context**

**Comment by mattjurczyk** [comment]
seeing these issues with the factor table

`> select * from okta_factor where factor_type = 'webauthn' limit 5

Error: okta: failed to populate column 'id': rpc error: code = Internal desc = transform FieldValue failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)

+--------+----+---------+-----------+-------------+---------+--------------+----------+--------+---------+----------+--------+-------+--------------------+--------+------+
| domain | id | user_id | user_name | factor_type | created | last_updated | provider | status | profile | embedded | verify | title | sp_connection_name | sp_ctx | _ctx |
+--------+----+---------+-----------+-------------+---------+--------------+----------+--------+---------+----------+--------+-------+--------------------+--------+------+
+--------+----+---------+-----------+-------------+---------+--------------+----------+--------+---------+----------+--------+-------+--------------------+--------+------+
> select * from okta_factor where factor_type = 'webauthn' limit 5
⠹ Executing query…^R

Error: okta: failed to populate column 'title': rpc error: code = Internal desc = transform FieldValue failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)

+--------+----+---------+-----------+-------------+---------+--------------+----------+--------+---------+----------+--------+-------+--------------------+--------+------+
| domain | id | user_id | user_name | factor_type | created | last_updated | provider | status | profile | embedded | verify | title | sp_connection_name | sp_ctx | _ctx |
+--------+----+---------+-----------+-------------+---------+--------------+----------+--------+---------+----------+--------+-------+--------------------+--------+------+
+--------+----+---------+-----------+-------------+---------+--------------+----------+--------+---------+----------+--------+-------+--------------------+--------+------+
> select * from okta_factor where factor_type = 'push' limit 5

Error: okta: context deadline exceeded (SQLSTATE HV000)

+--------+----+---------+-----------+-------------+---------+--------------+----------+--------+---------+----------+--------+-------+--------------------+--------+------+
| domain | id | user_id | user_name | factor_type | created | last_updated | provider | status | profile | embedded | verify | title | sp_connection_name | sp_ctx | _ctx |
+--------+----+---------+-----------+-------------+---------+--------------+----------+--------+---------+----------+--------+-------+--------------------+--------+------+
+--------+----+---------+-----------+-------------+---------+--------------+----------+--------+---------+----------+--------+-------+--------------------+--------+------+
> select * from okta_factor limit 10

Error: okta: failed to populate column 'id': rpc error: code = Internal desc = transform FieldValue failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)
`

**Comment by ParthaI** [comment]
Hello @mattjurczyk,

I'm sorry to hear that you're encountering issues.

I tried running the same query with different parameter values, and I consistently received results without any errors. The rows I retrieved include factors of type `token:software:totp`, `sms`, and `push`.

```
 select * from okta_factor where factor_type = 'sms' limit 5
+-----------------------+----------------------+----------------------+-------------------+-------------+---------------------------+---------------------------+----------+--------------------+---------------------------------+----------+--------+---------------------->
| domain                | id                   | user_id              | user_name         | factor_type | created                   | last_updated              | provider | status             | profile                         | embedded | verify | title                >
+-----------------------+----------------------+----------------------+-------------------+-------------+---------------------------+---------------------------+----------+--------------------+---------------------------------+----------+--------+---------------------->
| dev-89237458.okta.com | mbl1m6472anhxTgOE5d7 | 00u1kcfw5yDiVG80P5d7 | klsoef@gherot.com | sms         | 2021-08-30T18:24:44+05:30 | 2021-08-30T18:24:44+05:30 | OKTA     | PENDING_ACTIVATION | {"phoneNumber":"+919776252898"} | <null>   | <null> | mbl1m6472anhxTgOE5d7 >
+-----------------------+----------------------+----------------------+-------------------+-------------+---------------------------+---------------------------+----------+--------------------+---------------------------------+----------+--------+---------------------->

> select * from okta_factor where factor_type = 'push'
+-----------------------+----------------------+----------------------+-------------------+-------------+---------------------------+---------------------------+----------+--------+---------------------------------------------------------------------------------------->
| domain                | id                   | user_id              | user_name         | factor_type | created                   | last_updated              | provider | status | profile                                                                                >
+-----------------------+----------------------+----------------------+-------------------+-------------+---------------------------+---------------------------+----------+--------+---------------------------------------------------------------------------------------->
| dev-89237458.okta.com | opfg6o5fqcXWpMfKY5d7 | 00u1kcfw5yDiVG80P5d7 | klsoef@gherot.com | push        | 2024-04-02T23:07:34+05:30 | 2024-04-02T23:07:58+05:30 | OKTA     | ACTIVE | {"credentialId":"klsoef@gherot.com","deviceType":"SmartPhone_Android","keys":[{"e":"AQA>
+-----------------------+----------------------+----------------------+-------------------+-------------+---------------------------+---------------------------+----------+--------+---------------------------------------------------------------------------------------->
```

How is the query (`select * from okta_factor`) performing in your environment? Is it returning rows or showing any errors?

By the way, I have pushed a fix to the `fix-nil-pointer-error-for-factor` branch to address the nil pointer dereference error. If possible, could you please try building the plugin locally from this branch?

**Comment by mattjurczyk** [comment]
still seeing Error: okta: failed to populate column 'embedded': rpc error: code = Internal desc = transform FieldValue failed with panic runtime error: invalid memory address or nil pointer dereference (SQLSTATE HV000)

are you on Okta OIE or Classic. We're on OIE.

**Comment by ParthaI** [comment]
Hi @mattjurczyk,

I apologize for the delay in my response.

Yes, we have an Okta Classic account, which might be why I cannot replicate the error in our environment.

However, I have pushed a few changes to the fix-nil-pointer-error-for-factor branch to address the nil-pointer exception for the Okta OIE account.

Could you please try using the branch and share your observations with us? Your feedback would be greatly appreciated.

Steps to build the plugin from the branch `fix-nil-pointer-error-for-factor`:

- Clone the repository: git clone https://github.com/turbot/steampipe-plugin-okta.git
- Navigate to the plugin directory: cd steampipe-plugin-okta
- Checkout the branch: git checkout fix-nil-pointer-error-for-factor
- Build the plugin: make
- Run the query.

Thank you for your support and understanding!

**Comment by ParthaI** [comment]
Hello @mattjurczyk,

I was able to test it against both OIE and Classic accounts, and it worked fine in both cases.

I've raised a [PR](https://github.com/turbot/steampipe-plugin-okta/pull/137) to address the issue we discussed.

I apologize again for any inconvenience this may have caused.

Thanks!
